production:
  deployments:
  - environment: production
    production_environment: true

staging:
  auto_deploy_on: refs/heads/master
  deployments:
  - environment: staging
    production_environment: false

review:
  deployments:
  - environment: pr${{ pr }}
    transient_environment: true
    production_environment: false
